define

triggering-cascade sub rule
    when {
        (triggering: $triggering, triggered: $triggered) isa triggering-relationship;
        (triggering: $triggered, triggered: $triggered2) isa triggering-relationship;
    }
    then {
        (triggering: $triggering, triggered: $triggered2) isa triggering-relationship;
    };