match $rule sub rule; get $rule; undefine $rule;

define

functional_relationship_chain sub rule
    when {
        $rel (antecedent: $ant, consequent: $sub) isa functional_relationship;
        $inferred_rel (antecedent: $sub, consequent: $inferred_sub) isa functional_relationship;
    }
    then {
        (antecedent: $ant, consequent: $inferred_sub) isa functional_relationship;
    };
