define

# Attributes

text sub attribute, datatype string;
name sub attribute, datatype string;
valence sub attribute, datatype string;
uid sub attribute, datatype string;

# Entities

source sub entity
    has text
    has name
    has uid
    plays reference;

phrase sub entity
    has text
    plays subject
    plays predicate
    plays object
    plays changed;

named_entity sub entity
    has name
    plays changed;


# Relationships

entity_phrase_relationship sub relationship
    relates subject
    relates predicate
    relates object;

drive_change sub relationship
    relates changed
    has valence
    plays antecedent
    plays consequent;

functional_relationship sub relationship
    relates antecedent
    relates consequent

derivation sub relationship
    relates derived
    relates source;

# Roles

subject sub role;
predicate sub role;
object sub role;
antecedent sub role;
consequent sub role;
changed sub role;
referent sub role;
reference sub role;
derives_from sub role;
derived_from sub role;