define

# Attributes

name sub attribute, datatype string;
valence sub attribute, datatype string;
source-text sub attribute, datatype string;
source-name sub attribute, datatype string;
source-id sub attribute, datatype string;

# Entities

driven-concept sub entity
    # A biological concept whose 'drive' has increased or decreased
    has name
    has valence
    plays triggering
    plays triggered;

# Relationships

triggering-relationship sub relationship
    # Relate two causally-linked changes in drive
    relates triggering
    relates triggered
    has source-text
    has source-name
    has source-id;

# Roles

triggering sub role;
triggered sub role;
