match 
    $triggering_relationship (triggering: $triggering, triggered: $triggered) isa triggering-relationship;
    $triggering has name "B. fragilis";
    $triggered has name "spermine oxidase";
get
    $triggering_relationship;