match 
    $func_rel (antecedent: $ant, consequent: $cons) isa functional_relationship;
    $ant (changed: $ant_ent) isa drive_change has valence $ant_valence;
    $ent isa named_entity has name $ant_ent_name;
    $ant_ent_name "B. fragilis";
    $ant_valence "UP";
get
    $func_rel;