match 
    $triggering_relationship (triggering: $triggering, triggered: $triggered) isa triggering-relationship;
    $triggered has name "reactive oxygen species" has valence "UP";
get
    $triggering_relationship;